### ISSUE TITLE
Install failed on my machine

### ISSUE THREAD

**Issue by nickmeldrum** [stuartleeks/posh-azurecli#2]
Hey Stuart,

Great idea to do this. I tried the install on my machine and it unfortunately failed. If I get a moment I will debug myself, but just in case you wanted to see the error and have a look yourself I've pasted the error text below :)

"Do you want to run the script?
 NOTE: If you choose not to run the script, the installation will
 fail.
 Skip is an advanced option and most likely will never be wanted.

 1) yes
 2) no [Default - Press Enter]
 3) skip
1
 Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
 At C:\ProgramData\chocolatey\lib\posh-azurecli\tools\utils.ps1:8 char:52
-     $matches = $env:Path.Split(';') | %{{ join-path $_ $filename}} | ?{{ test-path  ...
-                                                    ~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
    PathCommand
    Found Azure CLI in C:\Users\nick.meldrum\AppData\Roaming\npm\azure.cmd C:\Users\nick.meldrum\AppData\Roaming\npm\azure.cmd
    Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
    At C:\ProgramData\chocolatey\lib\posh-azurecli\tools\utils.ps1:8 char:52
-     $matches = $env:Path.Split(';') | %{{ join-path $_ $filename}} | ?{{ test-path  ...
-                                                    ~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
    PathCommand
    Running 'azure --gen' to generate metadata files
    info:    Generating command metadata file: C:\Users\nick.meldrum\AppData\Roaming\npm\node_modules\azure-cli\lib\plugins.arm.json
    info:    Done
    info:    Generating command metadata file: C:\Users\nick.meldrum\AppData\Roaming\npm\node_modules\azure-cli\lib\plugins.asm.json
    info:    Done
    Creating profile: C:\Users\nick.meldrum\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
    Add posh-azurecli to profile
    posh-azurecli install not successful.
    Error while running 'C:\ProgramData\chocolatey\lib\posh-azurecli\tools\chocolateyInstall.ps1'.
    See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details.
Failures:
- posh-azurecli
  "

**Comment by stuartleeks** [comment]
Thanks for logging the issue! I'm guessing that there's part of your PATH environment variable that ahs an empty segment (e.g. "c:\SomePath**;;**C:\AnotherPath;C:\INeedMoreImagination" - note the double semi-colon).

I've just pushed 0.1.3 to the myget feed - can you try installing again and let me know if that fixes it?

Thanks!

**Comment by nickmeldrum** [comment]
BOOM - confirmed that fixed the error messages - nice turn around :)

**Comment by nickmeldrum** [comment]
I may well be being stupid here but I can't get it working - I'm assuming that the usage is along the lines of: type "azure " and hit the tab key and it should cycle through account/ mobile/ network/ site/ storage etc.?

**Comment by stuartleeks** [comment]
Have you opened a new PowerShell window after installing? I need to look at updating the installer so that it adds tab completion in the existing session (currently it installs it in your profile which is executed when you start a new session) I've created #3 for this :-)

**Comment by stuartleeks** [comment]
Can you also check which version of the CLI you have? I've realised that I depend on something only added in 0.9.7.

I've added a check to the installer for this and pushed that (posh-azurecli 0.1.4) to the myget feed. If you uninstall and reinstall posh-azurecli it should detect this condition now and fail to install.

**Comment by stuartleeks** [comment]
Update: I've just worked with a colleague who had some issues with it not working. It turned out that they had multiple installations of the CLI (one via NPM and one using the MSI). My code wasn't handling this. I've updated to 0.1.5 which takes the first installation found in the path.

Can you try this and let me know if it works for you?

Thanks, Stuart

**Comment by nickmeldrum** [comment]
Hey, sorry got caught up with other stuff, but had a chance to check tonight.
1. only installed azure once via npm
2. confirmed that even in new sessions it didn't work
3. checked azure version with `azure -v` and indeed it was 0.9.5
4. updated azure-cli with command `npm update azure-cli -g`
5. checked azure version with `azure -v` and it is now 0.9.7
6. uninstalled with the command `choco uninstall posh-azurecli`
7. reinstalled with command `choco install posh-azurecli -source 'https://www.myget.org/F/posh-azurecli/api/v2'`
8. new powershell session and still no autocomplete :smile:

**Comment by stuartleeks** [comment]
Hmmm - thanks for checking!

When you get chance, can you run each of the following commands in PowerShell and let me know the output?
- Get-Module
- GetAzureCmdPath
- GetAzureLibPath
- AzureCliExpansion "azure vm li"
- TabExpansion "azure vm li"

**Comment by stuartleeks** [comment]
Closing as moving the repo to readonly
