### ISSUE TITLE
Installation fails: Could not find azure cli (but it is there)

### ISSUE THREAD

**Issue by tomasaschan** [stuartleeks/posh-azurecli#4]
`Install-Module Posh-AzureCli` worked fine, and so did `Import-Module Posh-AzureCli`. But then:

```
C:\Users\tomas> Install-AzureCliCompletion
Reset-AzureCliCompletion : Could not find azure cli
At C:\Program Files\WindowsPowerShell\Modules\posh-azurecli\0.1.10\utils.ps1:34 char:9
+         Reset-AzureCliCompletion
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Reset-AzureCliCompletion

Add posh-azurecli to profile
```

However, Azure CLI _is_ there:

```
C:\Users\tomas> az --version
azure-cli (2.0.20)

acr (2.0.14)
acs (2.0.18)
appservice (0.1.19)
backup (1.0.2)
batch (3.1.6)
batchai (0.1.2)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.9)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.12)
core (2.0.20)
cosmosdb (0.1.14)
dla (0.0.13)
dls (0.0.16)
eventgrid (0.1.5)
extension (0.0.5)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.13)
keyvault (2.0.13)
lab (0.0.12)
monitor (0.0.11)
network (2.0.17)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.8)
redis (0.2.10)
resource (2.0.17)
role (2.0.14)
servicefabric (0.0.5)
sql (2.0.14)
storage (2.0.18)
vm (2.0.17)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\tomas\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
```

What am I missing here?

**Comment by stuartleeks** [comment]
Ah - apologies, this project has lagged behind quite a bit. So much in fact that it targets the old Azure CLI (the `azure` one rather than the `az` one). Maybe I should delete the repo to avoid confusion?

**Comment by tomasaschan** [comment]
Thanks for getting back on this!

I don't think you need to delete the repo - someone might find it useful as a baseline for a building module that works with `az` :) However, a note at the top of the Readme about this would probably be helpful.

**Comment by tomasaschan** [comment]
Actually, I'm going to make an attempt at porting this :)

It seems it relies heavily on the metadata from `azure --gen`, though, and [I can't figure out where to find the corresponding information from `az`](https://github.com/Azure/azure-cli/issues/4813), but once that's solved I'll be able to make a serious attempt.

**Comment by stuartleeks** [comment]
Closing (and updating readme)
